# DB 생성문
CREATE TABLE MEMBER (
	MEMBER_ID VARCHAR(255) NOT NULL,
	TEAM_ID VARCHAR(255),
	USERNAME VARCHAR(255),
	primary key (MEMBER_ID)
);

# DB 생성문 
CREATE TABLE TEAM (
	TEAM_ID VARCHAR(255),
    NAME VARCHAR(255),
    primary key (TEAM_ID)
);

/*DB 연관관계 수정문 
MEMBER 테이블을 수정하며 제약조건 명은 FK_MEMBER_TEAM
MEMBER TABLE의 TEAM_ID를 FK 지정
TEAM TABLE을 참조
*/
ALTER TABLE MEMBER
ADD constraint FK_MEMBER_TEAM 
foreign key (TEAM_ID)
references TEAM(TEAM_ID);

# INSERT 문 (Create)
INSERT INTO TEAM(TEAM_ID, NAME) VALUES('team1', '팀1');
INSERT INTO MEMBER(MEMBER_ID, TEAM_ID, USERNAME) VALUES ('member1','team1', '회원1');
INSERT INTO MEMBER(MEMBER_ID, TEAM_ID, USERNAME) VALUES ('member2','team1', '회원2');

# join으로 객체와 DB에서 패러다임 불일치 문제 확인
SELECT *
FROM MEMBER M
JOIN TEAM T ON T.TEAM_ID = M.TEAM_ID
WHERE M.MEMBER_ID = 'member1';
